apiVersion: apps/v1
kind: Deployment
metadata:
  name: phone-service
  namespace: monitoring
  labels:
    app: phone-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phone-service
  template:
    metadata:
      labels:
        app: phone-service
    spec:
      containers:
        - name: phone-service
          image: ghcr.io/hunh0w/ramen/phone-service:v1.0
          imagePullPolicy: IfNotPresent
          env:
            - name: KUBE_AI_BASE_URL
              value: http://kubeai.default.svc.cluster.local
---
apiVersion: v1
kind: Service
metadata:
  name: phone-service
  namespace: monitoring
  labels:
    app: phone-service
spec:
  selector:
    app: phone-service
  type: NodePort
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000