apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-fixer
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-fixer
  template:
    metadata:
      labels:
        app: ai-fixer
    spec:
      containers:
        - name: ai-fixer
          image: ghcr.io/hunh0w/ramen/ai-fixer:v1.0
          args: ["--kubeconfig=/config/kubeconfig.yaml"]
          volumeMounts:
            - name: kubeconfig
              mountPath: /config
              readOnly: true
          env:
            - name: AI_URL
              value: http://kubeai.default.svc.cluster.local
            - name: PHONE_SERVICE_URL
              value: http://phone-service.monitoring.svc.cluster.local:8000
            - name: GITHUB_URL
              value: https://github.com/Hunh0w/Ramen.git
            - name: GITHUB_TOKEN
              value: 
      volumes:
        - name: kubeconfig
          secret:
            secretName: kubeconfig