apiVersion: v1
kind: PersistentVolume
metadata:
  name: ps-pv
  namespace: monitoring
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/phone-service
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ps-pvc
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi