apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: app-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          resources:
            limits:
              cpu: "50m" # Increased to 50m from 10m for CPU
              memory: "64Mi" # Increased to 64Mi from 1Mi for RAM